name: deploy
on:
  push:
    branches:
      master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: build js
        run: npm run build
      - name: build toolkit
        run: ./build-toolkit
      - name: relase to gh-pages
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "<>"
          git --work-tree dist/ checkout --orphan gh-pages
          git --work-tree dist/ add --all
          git commit -m "[ci skip] release $(date)"
          git push --force --set-upstream origin gh-pages